### ISSUE TITLE
將 settings 改成 ENV

### ISSUE THREAD

**Issue by SammyLin** [commandp/mock-server#2]
這個要不要改成直接吃 ENV 呀。現在真的有點蠢=_=

https://github.com/commandp/mock-server/blob/186f4bb75346818f9cb55bf5a9a49b47e4aafb3e/app/uploaders/file_uploader.rb#L10

**Comment by gogojimmy** [comment]
那你為什麼要送 issue, 應該送個 PR 來啊！

**Comment by SammyLin** [comment]
我本來明天要幫你寫的～～ 不過看來你寫好惹 XD
